/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    'genuine-installation-media',
    'faq',
    'troubleshoot',
    {
      type: 'html',
      value: '<hr style="margin: 8px 0; border: 0; border-top: 1px solid #ddd;" />',
    },
    {
      type: 'category',
      label: 'Docs',
      items: ['hwid','ohook','tsforge','kms38','online_kms','chart','command_line_switches','check_activation_status','oem-folder','change_windows_edition','change_office_edition'],
    },
    {
      type: 'category',
      label: 'Manual Activation',
      items: ['manual_hwid_activation', 'manual_ohook_activation', 'manual_kms38_activation']
    },
	'guide_links',
	'unsupported_products_activation',
	'news',
	'changelog',
	'our_non-piracy_site',
	'contribute',
	'credits',
	'contactus',
  ],
  
};

export default sidebars;
